Label activation options technical details
webmappsrl/geohub pull request #28
Opened 2024-10-23 09:14 UTC by RubensGarofalo

2024-10-24 07:21 UTC, gemanzo requested changes

2024-10-24 07:21 UTC, gemanzo commented on app/Nova/App.php
> +            Heading::make('<p>This information is displayed in the technical details through the app.</p>')->asHtml(),
Aggiungere costrutto traduzione

2024-10-24 07:21 UTC, gemanzo commented on app/Traits/ConfTrait.php
> -        $data['OPTIONS']['show_favorites'] = $this->show_favorites;
Non togliere show_favorites per il momento

2024-10-24 07:21 UTC, gemanzo commented on app/Traits/ConfTrait.php
> +        $data['OPTIONS']['show_duration:forward'] = $this->table_details_show_duration_forward;
sostituire tutti i ':'con gli underscore '_'

2024-10-24 07:21 UTC, gemanzo commented on app/Traits/ConfTrait.php
> +        $data['OPTIONS']['show_duration:forward'] = $this->table_details_show_duration_forward;
Cambiare tutte le chiavi in camelCase

2024-10-24 07:21 UTC, gemanzo commented on database/migrations/2024_10_21_123704_add_new_options_to_apps_table.php
> +                'table_details_show_descent' => true,
$table->jsonb('table_details')->nullable()
'table_details->show_duration_forward'
$cast = [ 'table_details'=> array]

2024-10-28 05:27 UTC, peppedeka approved these changes

2024-10-28 05:27 UTC, merged